"""Market-implied characteristic function, and calibration in CF space.

Carr-Madan's out-of-the-money transform inverts algebraically. Writing
``y = log(S_T/F)`` for the forward-normalized log return, ``k = log(K/F)``,
and ``z(k)`` for the forward-normalized OTM option price (put below the
forward, call above it),

.. math::

    \\zeta(v) = \\int e^{ivk} z(k)\\,dk
             = \\frac{1 - \\varphi(v - i)}{v^2 - iv}
    \\qquad\\Longleftrightarrow\\qquad
    \\varphi(v - i) = 1 + iv(1 + iv)\\,\\zeta(v).

So the quoted chain *determines* the risk-neutral characteristic function on
the line ``Im(u) = -1``, in closed form, with

* no damping parameter ``alpha`` and therefore no implicit strike reweighting,
* no interpolation of quotes onto a continuum,
* no numerical inversion of anything.

Two structural consequences drive this module.

**The martingale condition is free.** At ``v = 0`` the identity forces
``phi(-i) = 1`` regardless of the quotes, because the prefactor vanishes. What
is imposed as a constraint elsewhere is an algebraic identity here.

**The transform is linear**, so the BBO box ``{z_j in [b_j, a_j]}`` has an
*exact* image at each frequency: a zonotope in the complex plane, centred on
the mid and generated by the half-spreads (:func:`cf_zonotope`). "The model is
inside the quoted market" is therefore an exact convex condition. None of the
machinery the implied-volatility loss required -- nonlinear inversion, a
fallback penalty for uninvertible prices, a vol-width normalization -- appears,
and neither does the escape hatch that fallback opened (see the protocol doc,
section 11.4).

Consistency with the production objective is exact, not approximate:

* implied volatility is strictly increasing in price, so the IV band and the
  price band have the *same* zero set -- verified at 0 disagreements over
  540,690 strike-model tests;
* on a Nyquist-complete frequency grid (:func:`nyquist_vmax`) the operator
  ``phi = 1 + M z`` is a bijection, so the price box pulls back to CF space
  with no relaxation -- verified at 0 mismatches over 132,459 strike-tests,
  round-trip error 2e-15.

The grid requirement is the one real trap. Resolving the *finest strike
spacing* needs ``v_max ~ pi / min(diff(k))``, which is far beyond what the
k-span alone suggests: on the 2026-08-10 SPXW chain, ``2 pi n / span`` gives
2178 and leaves the operator rank 164 of 201, while the correct 12452 gives
full rank at condition number 130. Undersample and the CF band condition
silently becomes a *strict relaxation* of the price box -- a model can look
inside in CF space while its prices sit outside the quotes.

**Score the model through the same operator, never against the exact CF.**
The tempting shortcut is to compare :func:`model_cf`, which is closed form and
13-23x cheaper than pricing, directly against the market zonotope. On a real
chain that is wrong. The trapezoid rule tracks the continuous transform only
while ``e^{ivk}`` is resolved, ``v << pi / max(diff(k))``, but the operator is
injective only for ``v >~ pi / min(diff(k))``. SPXW quotes 5-point strikes at
the money and 200-point strikes in the wings, so those thresholds sit at 90 and
4981 -- a factor of 56 apart, with no overlap. At ``v = 50`` the discrete
transform already carries 24% relative error, and MSVG scores 159.6 against the
exact CF where the priced route gives 1.35. Restricting to a uniformly spaced
strike run does merge the two regimes, but such a run covers only the dense
at-the-money region, where ``z`` has not decayed and truncation replaces
aliasing. Both routes are available; only the priced one is faithful.
"""

import numpy as np

from .markov_chain import markov_vg_cf
from .vg_process import VGParams, vg_cf

__all__ = [
    "otm_from_surface",
    "cf_from_otm",
    "model_cf",
    "trapezoid_weights",
    "cf_operator",
    "nyquist_vmax",
    "cf_zonotope",
    "zonotope_support",
    "zonotope_radius",
    "zonotope_excess",
    "cf_band_loss",
    "CFBand",
    "share_measure_bounds",
]


# --------------------------------------------------------------------------
# Market side: quotes -> characteristic function
# --------------------------------------------------------------------------
def otm_from_surface(surface, D_hat, A_hat, F_hat, strikes=None):
    """Forward-normalized OTM prices ``z(k)`` from the call-equivalent surface.

    ``surface`` carries call-equivalent BBO at every strike. Out-of-the-money
    means the put below the forward and the call above it; the put is recovered
    through the same parity relation that built the surface, so no new carry
    assumption enters. Returns ``(k, {side: z}, strikes)`` sorted by ``k``.
    """
    K = surface["strike"].to_numpy(float)
    if strikes is not None:
        keep = np.isin(K, np.asarray(strikes, float))
        surface, K = surface.loc[keep], K[keep]
    out = {}
    for side in ("bid", "ask", "mid"):
        call = surface[side].to_numpy(float)
        put = call - A_hat + D_hat * K
        out[side] = np.where(K >= F_hat, call, put) / (D_hat * F_hat)
    k = np.log(K / F_hat)
    order = np.argsort(k)
    return k[order], {s: v[order] for s, v in out.items()}, K[order]


def trapezoid_weights(k):
    """Quadrature weights for a possibly non-uniform ``k`` grid."""
    k = np.asarray(k, float)
    w = np.empty_like(k)
    w[1:-1] = 0.5 * (k[2:] - k[:-2])
    w[0] = 0.5 * (k[1] - k[0])
    w[-1] = 0.5 * (k[-1] - k[-2])
    return w


def cf_operator(k, v):
    """Complex matrix ``M`` with ``phi = 1 + M @ z`` on ``Im(u) = -1``."""
    v = np.atleast_1d(np.asarray(v, float))
    kernel = np.exp(1j * np.outer(v, np.asarray(k, float))) * trapezoid_weights(k)
    return kernel * (1j * v * (1.0 + 1j * v))[:, None]


def nyquist_vmax(k, safety=2.5):
    """Smallest ``v_max`` making :func:`cf_operator` full rank on this grid.

    Set by the *finest* strike spacing, not the k-span: two adjacent strikes are
    distinguishable only at frequencies that resolve their separation.
    """
    return float(safety * np.pi / np.min(np.diff(np.sort(np.asarray(k, float)))))


def cf_from_otm(k, z, v):
    """Characteristic function on ``Im(u) = -1`` implied by OTM prices."""
    v = np.atleast_1d(np.asarray(v, float))
    zeta = np.trapezoid(np.exp(1j * np.outer(v, k)) * z, k, axis=1)
    return 1.0 + 1j * v * (1.0 + 1j * v) * zeta


def model_cf(kind, params, tau, v):
    """Model CF of the *martingale* log return, evaluated at ``u = v - i``."""
    u = np.atleast_1d(np.asarray(v, float)) - 1j
    if kind == "vg":
        vg = VGParams(*params)
        raw = lambda w: vg_cf(w, tau, vg)
    else:
        s0, n0, t0, s1, n1, t1, l01, l10, p0 = params
        raw = lambda w: markov_vg_cf(w, tau, VGParams(s0, n0, t0),
                                     VGParams(s1, n1, t1), l01, l10, p0)
    compensator = np.log(raw(np.array([-1j]))[0])
    return np.exp(-1j * u * compensator) * raw(u)


# --------------------------------------------------------------------------
# The quote box, exactly, in CF space
# --------------------------------------------------------------------------
def cf_zonotope(k, z_bid, z_ask, v):
    """Centre and complex generators of the CF quote region per frequency.

    The attainable set at frequency ``i`` is exactly
    ``centre[i] + sum_j t_j gens[i, j]`` for ``t_j in [-1, 1]``.
    """
    v = np.atleast_1d(np.asarray(v, float))
    lift = cf_operator(k, v)
    centre = 1.0 + lift @ (0.5 * (np.asarray(z_bid) + np.asarray(z_ask)))
    gens = lift * (0.5 * (np.asarray(z_ask) - np.asarray(z_bid)))
    return centre, gens


def zonotope_support(centre, gens, theta):
    """Support function of the zonotope in direction ``theta``."""
    e = np.exp(-1j * theta)
    return np.real(e * centre) + np.abs(np.real(e[..., None] * gens)).sum(axis=-1)


def _directions(n_dir):
    return np.linspace(0.0, 2.0 * np.pi, int(n_dir), endpoint=False)


def zonotope_radius(centre, gens, n_dir=64):
    """Mean support radius: the natural scale to normalize an excess by."""
    r = np.stack([
        zonotope_support(centre, gens, np.full(centre.shape, t))
        - np.real(np.exp(-1j * t) * centre)
        for t in _directions(n_dir)
    ], axis=1)
    return r.mean(axis=1)


def zonotope_excess(phi, centre, gens, n_dir=64):
    """Distance by which ``phi`` protrudes from the zonotope, per frequency.

    Zero inside. Outside, the maximum over directions of (projection - support)
    is an exact lower bound on the Euclidean distance to the set, converging to
    it as ``n_dir`` grows.
    """
    theta = _directions(n_dir)
    proj = np.real(np.exp(-1j * theta)[None, :] * np.asarray(phi)[:, None])
    h = np.stack([zonotope_support(centre, gens, np.full(centre.shape, t))
                  for t in theta], axis=1)
    return np.maximum(proj - h, 0.0).max(axis=1)


def cf_band_loss(phi, centre, gens, weights=None, n_dir=64, eps=1e-12):
    """Zero inside the CF quote region; squared normalized excess outside.

    The direct analogue of the implied-volatility band loss, and exactly
    consistent with it on a Nyquist-complete grid -- but with no inversion
    step, hence no uninvertible-price case and no fallback penalty to exploit.
    """
    d = zonotope_excess(phi, centre, gens, n_dir)
    scale = np.maximum(zonotope_radius(centre, gens, n_dir), eps)
    per_v = (d / scale) ** 2
    if weights is None:
        return float(per_v.mean()), per_v
    weights = np.asarray(weights, float)
    return float((weights * per_v).sum() / weights.sum()), per_v


class CFBand:
    """Pre-compiled CF quote region for one chain: the calibration-loop object.

    The zonotope depends only on the quotes, so its support table can be built
    once and reused for every objective evaluation. That matters: recomputing
    the support per evaluation costs ~48 ms on a 201-strike chain at the
    Nyquist grid, against ~9 ms here -- the difference between the CF objective
    being five times dearer than the implied-volatility one and being its peer.
    Results are bit-identical to :func:`cf_band_loss`.
    """

    def __init__(self, k, z_bid, z_ask, v=None, n_dir=64, eps=1e-12):
        k = np.asarray(k, float)
        z_bid, z_ask = np.asarray(z_bid, float), np.asarray(z_ask, float)
        lo, hi = np.minimum(z_bid, z_ask), np.maximum(z_bid, z_ask)
        if v is None:
            v = np.linspace(0.0, nyquist_vmax(k), 2 * len(k))
        self.k, self.v = k, np.asarray(v, float)
        self.operator = cf_operator(k, self.v)
        self.centre, self.gens = cf_zonotope(k, lo, hi, self.v)
        theta = _directions(n_dir)
        self._cos, self._sin = np.cos(theta), np.sin(theta)
        self._support = np.stack(
            [zonotope_support(self.centre, self.gens, np.full(self.centre.shape, t))
             for t in theta], axis=1)
        self._radius = np.maximum(zonotope_radius(self.centre, self.gens, n_dir), eps)

    def cf_of_prices(self, z_model):
        """Model OTM prices on this chain's strikes -> CF on ``Im(u) = -1``."""
        return 1.0 + self.operator @ np.asarray(z_model, float)

    def excess(self, phi):
        """Per-frequency protrusion of ``phi`` from the quote region."""
        phi = np.asarray(phi)
        proj = np.real(phi)[:, None] * self._cos + np.imag(phi)[:, None] * self._sin
        return np.maximum(proj - self._support, 0.0).max(axis=1)

    def loss(self, phi):
        """Zero inside the quote region; mean squared normalized excess outside."""
        return float(np.mean((self.excess(phi) / self._radius) ** 2))

    def fraction_inside(self, phi):
        """Share of frequencies at which the model is inside the quoted market."""
        return float((self.excess(phi) == 0).mean())

    def loss_from_prices(self, prices, strikes, D_hat, A_hat, F_hat, guard=1e12):
        """CF band loss from model call prices, with the no-arbitrage cone enforced.

        The guard is not optional, and the reason is a real asymmetry between
        the two objectives. Both share an exact zero set, but only the
        implied-volatility loss enforces ``(A - D K)_+ <= C <= A`` *implicitly*:
        a price outside that range admits no implied volatility and collects the
        uninvertible penalty. The CF loss has no inversion step and so no such
        reflex -- a wing price below intrinsic is a tiny absolute displacement
        and barely registers.

        Left unguarded on the 2026-08-10 chain, the CF-fitted VG scores CF 0.122
        against the IV-fitted VG's 7.42, while its implied-volatility loss is
        1213.8 against 10.06. Restricted to the strikes where both objectives
        are defined it scores 22.5: the whole 54x gap was 24 strikes with no
        implied volatility.

        The tolerance must be relative to intrinsic, not to ``A``. Carr-Madan
        interpolates in log-moneyness, so deep-ITM prices carry a few cents of
        absolute error against the intrinsic floor -- 2.8 cents on a \\$2169
        option here, which an absolute ``1e-4 * A`` tolerance rightly admits and
        which is not an arbitrage. What that tolerance wrongly admits is the
        far wing, where intrinsic is zero and the model returns *negative*
        prices; those are caught by non-negativity instead.
        """
        prices = np.asarray(prices, float)
        strikes = np.asarray(strikes, float)
        if not np.all(np.isfinite(prices)) or np.any(prices < 0.0):
            return float(guard)
        lower = np.maximum(A_hat - D_hat * strikes, 0.0)
        tol = np.maximum(1e-5 * lower, 1e-8 * A_hat)
        if np.any(prices < lower - tol) or np.any(prices > A_hat * (1.0 + 1e-8)):
            return float(guard)
        put = prices - A_hat + D_hat * strikes
        z = np.where(strikes >= F_hat, prices, put) / (D_hat * F_hat)
        return self.loss(self.cf_of_prices(z))


# --------------------------------------------------------------------------
# Model-free consequences of linearity
# --------------------------------------------------------------------------
def share_measure_bounds(k, z_bid, z_ask, tau):
    """Exact model-free interval for the share-measure moments of ``y``.

    Because ``phi(v - i)`` is the characteristic function of ``y`` under the
    share measure, its low-order Taylor coefficients are *linear* functionals
    of ``z``. Expanding ``iv(1 + iv)e^{ivk} = iv - v^2(k + 1) + O(v^3)``,

        phi(v - i) = 1 + i v S_0 - v^2 S_1 + O(v^3),
        S_0 = sum_j w_j z_j,   S_1 = sum_j w_j (k_j + 1) z_j,

    so each has an exact interval over the quote box, attained at a vertex --
    no optimization, no model. This is the tightest statement the quotes make
    on their own, and any admissible model must land inside it.
    """
    k = np.asarray(k, float)
    w = trapezoid_weights(k)
    z_bid, z_ask = np.asarray(z_bid, float), np.asarray(z_ask, float)
    centre, radius = 0.5 * (z_bid + z_ask), 0.5 * np.abs(z_ask - z_bid)
    s0_c, s0_r = float(w @ centre), float(np.abs(w) @ radius)
    s1_c, s1_r = float((w * (k + 1)) @ centre), float(np.abs(w * (k + 1)) @ radius)
    m2_lo, m2_hi = 2.0 * (s1_c - s1_r), 2.0 * (s1_c + s1_r)
    sd_lo = np.sqrt(max(m2_lo - (s0_c + s0_r) ** 2, 0.0))
    sd_hi = np.sqrt(max(m2_hi - (s0_c - s0_r) ** 2, 0.0))
    return {
        "mean": (s0_c - s0_r, s0_c + s0_r),
        "second_moment": (m2_lo, m2_hi),
        "sd": (sd_lo, sd_hi),
        "sd_annualized": (sd_lo / np.sqrt(tau), sd_hi / np.sqrt(tau)),
    }
